services:
  simpledockerdashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simpledockerdashboard
    restart: always
    volumes:
      - ./www_data:/var/www/html
      - ./php_data/php.ini:/usr/local/etc/php/php.ini
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DASHBOARD_USER=${DASHBOARD_USER}
      - DASHBOARD_PASS=${DASHBOARD_PASS}
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 256M
    ports:
      - "6080:80"
